# Generated by Django 5.2 on 2025-04-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='daily_fine_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Daily fine rate for late returns', max_digits=6),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_fine',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total fine accumulated', max_digits=10),
        ),
    ]
