# Generated by Django 5.2 on 2025-04-07 14:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notify_subscribers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 14, 36, 1, 180385, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('SCI', 'Science'), ('HIS', 'History'), ('BIO', 'Biography')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
